# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mafia.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmafia.proto\"\x19\n\x04Room\x12\x11\n\troom_name\x18\x01 \x01(\t\")\n\x06Player\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\"\x1e\n\x0bPlayersList\x12\x0f\n\x07players\x18\x01 \x03(\t\"+\n\rNotifications\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\"2\n\x11StartGameResponse\x12\x0f\n\x07players\x18\x01 \x03(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"5\n\x04Vote\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\troom_name\x18\x02 \x01(\t\x12\x0c\n\x04vote\x18\x03 \x01(\t\",\n\x0cVoteResponse\x12\x0e\n\x06player\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xa0\x03\n\x0eSoaMafiaServer\x12+\n\x10RegistratePlayer\x12\x07.Player\x1a\x0c.PlayersList\"\x00\x12\x31\n\x12NotificationStream\x12\x07.Player\x1a\x0e.Notifications\"\x00\x30\x01\x12\x1f\n\nDisconnect\x12\x07.Player\x1a\x06.Empty\"\x00\x12*\n\tStartGame\x12\x07.Player\x1a\x12.StartGameResponse\"\x00\x12\x1a\n\x05Ready\x12\x07.Player\x1a\x06.Empty\"\x00\x12\"\n\x08SendVote\x12\x05.Vote\x1a\r.VoteResponse\"\x00\x12%\n\x0bMafiaChoice\x12\x05.Vote\x1a\r.VoteResponse\"\x00\x12,\n\x12\x43ommissionerChoice\x12\x05.Vote\x1a\r.VoteResponse\"\x00\x12%\n\x0c\x41livePlayers\x12\x05.Room\x1a\x0c.PlayersList\"\x00\x12%\n\x0cMafiaPlayers\x12\x05.Room\x1a\x0c.PlayersList\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mafia_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOM._serialized_start=15
  _ROOM._serialized_end=40
  _PLAYER._serialized_start=42
  _PLAYER._serialized_end=83
  _PLAYERSLIST._serialized_start=85
  _PLAYERSLIST._serialized_end=115
  _NOTIFICATIONS._serialized_start=117
  _NOTIFICATIONS._serialized_end=160
  _STARTGAMERESPONSE._serialized_start=162
  _STARTGAMERESPONSE._serialized_end=212
  _VOTE._serialized_start=214
  _VOTE._serialized_end=267
  _VOTERESPONSE._serialized_start=269
  _VOTERESPONSE._serialized_end=313
  _EMPTY._serialized_start=315
  _EMPTY._serialized_end=322
  _SOAMAFIASERVER._serialized_start=325
  _SOAMAFIASERVER._serialized_end=741
# @@protoc_insertion_point(module_scope)
